Qs editor interfaces questionunit
sunbird-content-plugins/org.ekstep.questionunit pull request #3
Opened 2018-06-22 11:30 UTC by JagadishPujari

2018-06-22 11:55 UTC, manojchandrashekar requested changes
JSDocs comments needed. Check `renderer/plugin.js`

2018-07-06 05:42 UTC, manojchandrashekar approved these changes

2018-07-06 05:42 UTC, manojchandrashekar commented
@vinukumar-vs FYA

2018-07-09 09:12 UTC, vinukumar-vs commented on editor/plugin.js
> +    this.__proto__.__proto__._data = data;
this.__proto__.__proto__._data this is not the right way of coding.

2018-07-09 09:12 UTC, vinukumar-vs commented on editor/plugin.js
> +    this.__proto__.__proto__._data = data;
_proto._proto should not use. This is resolved last time with @manojchandrashekar .
Please change the code.

2018-07-09 09:12 UTC, vinukumar-vs commented on editor/plugin.js
> +    ecEditor.addEventListener("org.ekstep.questionunit:compiled",function(){
Rename the event name "org.ekstep.questionunit.ready". 
Use it like this -> instance.manifest.id + ":ready"

2018-07-09 09:12 UTC, vinukumar-vs commented on editor/plugin.js
> +    ecEditor.addEventListener("org.ekstep.questionunit:compiled",function(){
Change the name "org.ekstep.questionunit.compiled" to "org.ekstep.questionunit.ready"

use it like this.manifest.id + ":ready"

Change the name in all the places(other plugins as well)

2018-07-09 09:13 UTC, vinukumar-vs requested changes

2018-07-09 09:13 UTC, vinukumar-vs commented on editor/plugin.js
> +    ecEditor.addEventListener("org.ekstep.questionunit:compiled",function(){
Update this event name.

2018-07-13 07:20 UTC, vinukumar-vs commented on editor/plugin.js
> +      ecEditor.dispatchEvent(instance.manifest.id + ":editquestion",data);
Change the name "editquestion" to "updateForm"

2018-07-13 07:20 UTC, vinukumar-vs commented on editor/plugin.js
> +      ecEditor.dispatchEvent(instance.manifest.id + ":editquestion",data);
Update the JSDOC with event fireing from which class

2018-07-13 07:21 UTC, vinukumar-vs approved these changes

2018-07-13 07:22 UTC, merged